# Generated by Django 4.2.3 on 2023-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='기업이름')),
                ('brand_intro', models.TextField(verbose_name='기업소개')),
                ('brand_subcounts', models.IntegerField(default=0, verbose_name='구독수')),
            ],
        ),
    ]
