# Generated by Django 4.2.3 on 2023-08-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_category_popup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popup_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='팝업이미지'),
        ),
    ]
