# Generated by Django 4.2.3 on 2023-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_popup_popup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_state',
            field=models.IntegerField(default=0, null=True, verbose_name='오픈1_예정2'),
        ),
    ]
