# Generated by Django 4.2.3 on 2023-08-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_alter_popup_popup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_detailplace',
            field=models.TextField(null=True, verbose_name='실제위치'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_category',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.category'),
        ),
    ]
