# Generated by Django 4.2.3 on 2023-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_alter_popup_popup_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_burndate',
            field=models.DateField(auto_now=True, verbose_name='생성날짜'),
        ),
    ]
