# Generated by Django 4.2.3 on 2023-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_brand_brand_burndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_burndate',
            field=models.DateField(verbose_name='생성날짜'),
        ),
    ]
