# Generated by Django 4.2.3 on 2023-08-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_alter_brand_brand_burndate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_burndate',
            new_name='brand_borndate',
        ),
    ]
