# Generated by Django 4.2.3 on 2023-08-08 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0011_rename_brand_burndate_brand_brand_borndate'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_like_people',
            field=models.ManyToManyField(blank=True, related_name='like_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
