# Generated by Django 4.2.3 on 2023-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_alter_brand_brand_like_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_closetime',
            field=models.TimeField(auto_now=True, verbose_name='마감시간'),
        ),
        migrations.AddField(
            model_name='popup',
            name='popup_opentime',
            field=models.TimeField(auto_now=True, verbose_name='오픈시간'),
        ),
    ]
