# Generated by Django 4.2.3 on 2023-08-08 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0016_alter_popup_popup_closetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_like_people',
            field=models.ManyToManyField(blank=True, related_name='popup', to=settings.AUTH_USER_MODEL),
        ),
    ]
