# Generated by Django 4.2.3 on 2023-08-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0019_brand_brand_image_brandimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_image',
        ),
    ]
