# Generated by Django 4.2.3 on 2023-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0020_remove_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_simple_info',
            field=models.CharField(default='', max_length=150, verbose_name='간단소개'),
        ),
    ]
