# Generated by Django 4.2.3 on 2023-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0022_remove_popup_popup_image_popup_popup_add_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popup_add_info',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='더많은정보'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_date',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='운영기간'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_operation',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='기획/운영'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_simple_info',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='간단소개'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='popup_time',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='운영시간'),
        ),
    ]
