# Generated by Django 4.2.3 on 2023-08-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0024_brand_brand_detail_image_brand_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.IntegerField(default=0, verbose_name='타입_1브랜드/2_아트스트'),
        ),
    ]
