# Generated by Django 4.2.3 on 2023-08-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0026_brandcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brandcategory'),
        ),
    ]
