# Generated by Django 4.2.3 on 2023-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0027_brand_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='popup_state',
            field=models.IntegerField(default=0, null=True, verbose_name='오픈1_예정2_종료3'),
        ),
    ]
