# Generated by Django 4.2.3 on 2023-08-14 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brand', '0028_alter_popup_popup_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_reservation_date', models.DateField(verbose_name='팝업예약날짜')),
                ('popup_reservation_time', models.CharField(max_length=100, verbose_name='팝업예약시간')),
                ('popup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.popup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
