# Generated by Django 4.2.3 on 2023-08-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0029_popupreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupreservation',
            name='popup_reservation_date',
            field=models.CharField(max_length=100, verbose_name='팝업예약날짜'),
        ),
    ]
