# Generated by Django 4.2.3 on 2023-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0030_alter_popupreservation_popup_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupreservation',
            name='popup_reservation_date',
            field=models.DateField(verbose_name='팝업예약날짜'),
        ),
    ]
