# Generated by Django 4.2.3 on 2023-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0031_alter_popupreservation_popup_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_intro',
            field=models.TextField(verbose_name='메인소개'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=100, verbose_name='한 줄 소개'),
        ),
    ]
