# Generated by Django 4.2.3 on 2023-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0033_brand_brand_simple_intro_alter_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_about_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='추가링크'),
        ),
    ]
