# Generated by Django 4.2.3 on 2023-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0034_brand_brand_about_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_simple_intro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='한 줄 소개'),
        ),
    ]
