# Generated by Django 4.2.3 on 2023-08-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0037_brand_brand_subscribe_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='popup_map_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지도위치'),
        ),
    ]
