# Generated by Django 4.2.3 on 2023-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpost',
            name='brandpost_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='메인이미지'),
        ),
    ]
