# Generated by Django 4.2.3 on 2023-08-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandpost', '0002_brandpost_brandpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandpost',
            name='brandpost_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='포스트이미지'),
        ),
    ]
