# Generated by Django 4.2.3 on 2023-08-11 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_password', models.CharField(max_length=50, verbose_name='결제비밀번호')),
                ('bank', models.CharField(max_length=50, verbose_name='은행')),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('card_number', models.CharField(max_length=50, verbose_name='카드번호')),
                ('max_date', models.DateField(verbose_name='카드유효기간')),
                ('cvc', models.CharField(max_length=50, verbose_name='cvc')),
                ('card_password', models.CharField(max_length=50, verbose_name='카드비밀번호')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
