# Generated by Django 4.2.3 on 2023-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='결제비밀번호'),
        ),
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='은행'),
        ),
        migrations.AlterField(
            model_name='card',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='계좌번호'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카드번호'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카드비밀번호'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cvc'),
        ),
        migrations.AlterField(
            model_name='card',
            name='max_date',
            field=models.DateField(blank=True, null=True, verbose_name='카드유효기간'),
        ),
    ]
