# Generated by Django 4.2.3 on 2023-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_account_password_alter_card_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='max_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카드유효기간'),
        ),
    ]
