# Generated by Django 4.2.3 on 2023-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_place_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='팝업공간사진')),
                ('popup_place_title', models.CharField(max_length=100, verbose_name='팝업공간이름')),
                ('popup_place_location', models.CharField(max_length=100, verbose_name='팝업공간위치')),
                ('popup_place_floor', models.CharField(max_length=50, verbose_name='팝업공간층수')),
                ('popup_place_area', models.CharField(max_length=50, verbose_name='팝업공간연면적')),
                ('popup_count', models.IntegerField(default=0, null=True, verbose_name='팝업횟수')),
                ('popup_place_intro', models.TextField(max_length=500, verbose_name='공간소개')),
                ('popup_place_point', models.TextField(max_length=300, verbose_name='주요포인트')),
                ('popup_place_recom', models.CharField(max_length=200, verbose_name='공간활용추천')),
                ('electricity', models.IntegerField(default=0, verbose_name='전기사용')),
                ('warehouse', models.IntegerField(default=0, verbose_name='창고사용')),
                ('freight', models.IntegerField(default=0, verbose_name='화물 E/V')),
                ('parking', models.IntegerField(default=0, verbose_name='주차지원')),
                ('pkey', models.IntegerField(default=0, verbose_name='팝업공간pk')),
            ],
        ),
    ]
