# Generated by Django 4.2.3 on 2023-08-08 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popup_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupplace',
            name='popup_place_like_people',
            field=models.ManyToManyField(blank=True, related_name='popupplace', to=settings.AUTH_USER_MODEL),
        ),
    ]
