# Generated by Django 4.2.3 on 2023-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_place', '0003_remove_popupplace_popup_place_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupplace',
            name='popup_place_like',
            field=models.IntegerField(default=0, verbose_name='팝업장소좋아요수'),
        ),
    ]
