# Generated by Django 4.2.3 on 2023-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_place', '0004_popupplace_popup_place_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupplace',
            name='popup_place_like',
            field=models.IntegerField(default=0, null=True, verbose_name='팝업장소좋아요수'),
        ),
    ]
