# Generated by Django 4.2.3 on 2023-08-11 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popup_place', '0005_alter_popupplace_popup_place_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupplace',
            name='popup_place_basement_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='지하층'),
        ),
        migrations.AddField(
            model_name='popupplace',
            name='popup_place_ground_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='지상층'),
        ),
        migrations.AlterField(
            model_name='popupplace',
            name='popup_place_like_people',
            field=models.ManyToManyField(blank=True, related_name='popupplaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
