# Generated by Django 4.2.3 on 2023-08-11 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popup_place', '0006_popupplace_popup_place_basement_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupPlaceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popupplace_reserved_floor', models.IntegerField(null=True, verbose_name='팝업공간예약층')),
                ('popupplace_reserved_date', models.CharField(max_length=100, verbose_name='팝업공간날짜')),
                ('popupplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popup_place.popupplace')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
