# Generated by Django 4.2.3 on 2023-08-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_place', '0007_popupplacereservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupplacereservation',
            name='popupplace_reserved_floor',
        ),
        migrations.AddField(
            model_name='popupplacereservation',
            name='popupplace_reserved_basement_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='팝업공간예약지상층'),
        ),
        migrations.AddField(
            model_name='popupplacereservation',
            name='popupplace_reserved_ground_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='팝업공간예약지하층'),
        ),
    ]
