# Generated by Django 4.2.3 on 2023-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup_place', '0008_remove_popupplacereservation_popupplace_reserved_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupplace',
            name='popup_place_title',
            field=models.CharField(max_length=200, verbose_name='팝업공간이름'),
        ),
    ]
